import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    in-out property <int> display: 0;
    
    callback button_clicked(int);


    VerticalLayout {

        height: 400px;
        width: 300px;

        Text {
            width: 300px;
            height: 200px;

            horizontal-alignment: center;
            vertical-alignment: center;

            font-size: 50px;

            text: display;
        }

        HorizontalLayout {


            Button {
                width: 75px;
                height: 50px;

                text: "7";
                clicked => {button_clicked(7);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "8";
                clicked => {button_clicked(8);}
            }
            test :=Button {
                width: 75px;
                height: 50px;
                text: "9";

                clicked => {button_clicked(9);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "/";
            }
        }
        HorizontalLayout {

            Button {
                width: 75px;
                height: 50px;

                text: "4";
                clicked => {button_clicked(4);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "5";
                clicked => {button_clicked(5);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "6";
                clicked => {button_clicked(6);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "x";
            }
        }
        HorizontalLayout {

            Button {
                width: 75px;
                height: 50px;

                text: "1";
                clicked => {button_clicked(1);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "2";
                clicked => {button_clicked(2);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "3";
                clicked => {button_clicked(3);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "-";
            }
        }
        HorizontalLayout {

            Button {
                width: 75px;
                height: 50px;

                text: "AC";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "0";
                clicked => {button_clicked(0);}
            }
            Button {
                width: 75px;
                height: 50px;
                text: "=";
                clicked => {button_clicked(10);}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "+";
            }
        }

    }

        
}
