import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    property <int> results;

    VerticalLayout {

        height: 400px;
        width: 300px;

        Text {
            width: 300px;
            height: 200px;

            horizontal-alignment: center;
            vertical-alignment: center;

            font-size: 50px;

            text: results;
        }

        HorizontalLayout {


            Button {
                width: 75px;
                height: 50px;

                text: "7";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "8";
            }
            test :=Button {
                width: 75px;
                height: 50px;
                text: "9";

                clicked => {results = 9}
            }
            Button {
                width: 75px;
                height: 50px;

                text: "/";
            }
        }
        HorizontalLayout {

            Button {
                width: 75px;
                height: 50px;

                text: "4";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "5";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "6";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "x";
            }
        }
        HorizontalLayout {

            Button {
                width: 75px;
                height: 50px;

                text: "1";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "2";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "3";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "-";
            }
        }
        HorizontalLayout {

            Button {
                width: 75px;
                height: 50px;

                text: "AC";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "0";
            }
            Button {
                width: 75px;
                height: 50px;
                text: "=";
            }
            Button {
                width: 75px;
                height: 50px;

                text: "+";
            }
        }

    }

        
}
